name: mri
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.6
  - pytorch=1.12.1
  - numpy
  - matplotlib
  - scikit-learn

pip:
  - ipykernel
  - h5py
  - torchkbnufft
  - pyaml
  - git+https://github.com/khammernik/medutils.git